from pydantic import BaseModel, Field
from typing import Optional

# ---------------------------------------------------------
# Request Schemas (Data coming FROM the React Frontend)
# ---------------------------------------------------------

class AskRequest(BaseModel):
    """
    Schema for the incoming question from the student.
    """
    # The actual question text. We enforce a minimum length to avoid empty/junk queries.
    question: str = Field(..., min_length=2, description="The question asked by the student")
    
    # Optional student ID, prepared for rate-limiting and auth implementation TODO: Implement actual authentication and rate-limiting logic using this field
    student_id: Optional[str] = Field(None, description="Optional student ID for tracking and rate limiting")


# ---------------------------------------------------------
# Response Schemas (Data going TO the React Frontend)
# ---------------------------------------------------------

class AskResponse(BaseModel):
    """
    Schema for the outgoing answer generated by the AI.
    """
    # The natural language answer generated by the AI (or the fallback message)
    answer: str = Field(..., description="The generated answer to display to the user")
    
    # The classification of the question (e.g., "Schedule", "General", "Location")
    category: str = Field(..., description="The automated category classification of the question")